### ISSUE TITLE
The QR bill guidelines do not specify how foreign address should be printed

### ISSUE THREAD

**Issue by epsitec** [swico/qr-bill#1]
Neither Version 2.1 of the [QR-bill Implementation Guidelines](https://www.paymentstandards.ch/dam/downloads/ig-qr-bill-de.pdf) nor the [Style Guide](https://www.paymentstandards.ch/dam/downloads/style-guide-de.pdf) explain how foreign addresses should be printed on the QR bill.

The question is open and we are waiting for SIX to give us additional guidelines.

**Comment by epsitec** [comment]
SIX replied:

- When the country code is `CH` or `LI` it should not be printed.
- Otherwise, it should be printed.

I am still trying to get an official layout guideline. Specifically, where and how should the country code be printed (for France, the ISO code is `FR` however the postal code is just `F`; using `FR` makes for strange looking international addresses).

**Comment by epsitec** [comment]
SIX confirmed that the country code has to appear before the ZIP code, as stored in the XML, that is as a two-letter ISO language code.

**Comment by gexclaude** [comment]
Interesting, what was the exact answer? And do you know if it will be added to IG or style guide or at least to the FAQs (https://www.paymentstandards.ch/de/home/software-partner/faq.html)?

I asked on 6.12.2018:
> Ist es korrekt, dass mit der überarbeiteten QR-Rechnung 2.0 der Landescode nicht mehr auf dem Zahlteil und dem Empfangsschein aufgedruckt werden?
Entsprechend fehlt das Land vollständig in den aufgedruckten Informationen.

And I got as an answer on 3.1.2019 from PM Six:

> Korrekt, der Ländercode braucht der PLZ nicht vorangestellt zu werden. Da es sich bei der QR-Rechnung um ein inländisches Verfahren handelt (Schweiz und Liechtenstein), bietet diese Information im Sichtteil keinen Mehrwert. Es steht Ihnen aber frei, den Ländercode dennoch anzudrucken.

**Comment by epsitec** [comment]
@gexclaude the replies you got are in line with what SIX replied earlier this January and February. As for the plans to update the Implementation Guideline, only SIX knows ;-)

**Comment by gexclaude** [comment]
But do you print the alpha-2 code in front of the ZIP?

**Comment by epsitec** [comment]
Not if it is `CH` or `LI`.

**Comment by gexclaude** [comment]
Agree, but for the others. Therefore I assume you print it with space, e.g. "DE 10179 Berlin-Mitte"

We will adjust our solutions as well, but I'd like to see SIX giving an official statement on this.

**Comment by epsitec** [comment]
I don't think you will get an official statement on this from SIX until a new IG gets published.
I would do as you suggest. Either with a space or with a dash. It does not really matter, as the text will only be here to confirm what's in the QR code itself. I've heard that some banks will do OCR on the text in order to match it with the information stored in the QR code, but as nothing explicit is defined for the country code, they'll have to keep the matching very tolerant.
